default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: exmpl_dev 

test:
  <<: *default
  database: exmpl_test

production:
  <<: *default
  database: exmpl_prod
